### ISSUE TITLE
Initial testing

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-themes/thanksroy#1]
This is a general testing issue for the first release of Thanks, Roy for Omeka S.

**Comment by mebrett** [comment]
First thing I'm noticing is that the primary menu doesn't seem to want to expand to show child pages? 
I've looked at http://dev.omeka.org/mebrett/testomekas/s/publicviews/page/allblocks in Chrome, Firefox and Safari. If my mouse is on a parent page, a small triangle appears which seems like it should allow that section to expand, but it doesn't seem to work?

**Comment by kimisgold** [comment]
I think this was a button color inheritance issue. It should now be resolved in https://github.com/omeka-s-themes/thanksroy/commit/79d31e8c00efd41382a9006174f1ee79fc171316.

**Comment by mebrett** [comment]
Thanks! That fixed it.
I like the way that there's automatically a table of contents between the main menu and the content _unless_ a table of contents block is added to the page. I do wonder about it taking up too much screen real estate?

I'm having an error with the browse preview block, which you should be able to [see here](http://dev.omeka.org/mebrett/testomekas/s/publicviews/page/allblocks). It's returning the following for each item which should display:
```
Warning: in_array() expects parameter 2 to be array, null given in /var/www/html/mebrett/testomekas/themes/thanksroy/view/common/block-layout/browse-preview.phtml on line 20

Warning: in_array() expects parameter 2 to be array, null given in /var/www/html/mebrett/testomekas/themes/thanksroy/view/common/block-layout/browse-preview.phtml on line 25

Warning: in_array() expects parameter 2 to be array, null given in /var/www/html/mebrett/testomekas/themes/thanksroy/view/common/block-layout/browse-preview.phtml on line 28
```

**Comment by kimisgold** [comment]
I had forgotten I'd been looking at a new browse preview feature branch when I copied over the partial from the core to customize for this theme. It should be fixed now in https://github.com/omeka-s-themes/thanksroy/commit/76377c78ec105551ea57c37e2b783d188ed5845f.

**Comment by mebrett** [comment]
Looking good - I appreciate the ability to change banner text color! Found one thing, but it's cross-theme so I'm putting it elsewhere. 

Numeric Data Type additions to the advanced item search form could use some tweaking: 
![Screen Shot 2020-11-13 at 9 57 08 AM](https://user-images.githubusercontent.com/2314070/99085778-9defe980-2596-11eb-98fd-139b8c2b7285.png)
see http://dev.omeka.org/mebrett/testomekas/s/publicviews/item/search
