### ISSUE TITLE
Language/Locale setting on site

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-themes/thanksroy#12]
The Browse page (when the site has a language and the "filter values" checkbox is checked) doesn't display the correct language-tagged values (title or description) where available in this theme. It will show the correct values on the item view page. It also shows the correct title in search results.

**Comment by sharonmleon** [comment]
I'm pretty sure this is happening in other themes too. I saw it earlier today with Center Row and Freedom with the Browse Preview block.

**Comment by zerocrates** [comment]
Browse views in this theme just look to be generally out of date; try with latest pull which includes the feature.

**Comment by allanaaa** [comment]
This works on basic browse pages but when I do a browse page with a query (e.g. still image class items) everything defaults back to what I assume is the first value.

http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-omeka-s-site/item?resource_class_id%5B%5D=33


Extra strangely, when I added this page in the navigation, it defaulted to added mapping parameters. You can see this unedited on the "browse base resource" link, where the language is filtering correctly:

http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-omeka-s-site/item?resource_template_id%5B%5D=1&has_markers=&mapping_address=&mapping_radius=&mapping_radius_unit=km

I assume that's a Mapping overreach I should file there, but I thought you better look into it first.

**Comment by allanaaa** [comment]
Okay, the first part is not a theme issue - when a browse query is set, it mostly does not use the correct locale filtering. This is on a site with locale filtering and custom browse properties set. It will display the correct language when available but fall back on the first value when not available, insteaad of displaying [No title] and an empty description, which is what's happening on the basic "Browse items" page.

A browse query with a resource template works, but a browse query with a class does not, and a browse query with a property value does not.
