### ISSUE TITLE
Test configurable page blocks

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-themes/thanksroy#3]
This is the theme-specific issue for omeka/omeka-s#1859. Please test this using the latest version of Omeka S on the `develop` branch.

Thanks, Roy now supports configurable resource page blocks. On a site's theme settings panel, select Thanks, Roy's "Configure resource pages" button. Test that blocks can be reordered, removed, and readded on the show views of items, media, and item sets. Thanks, Roy only has a single "Main" block region.

**Comment by katknow** [comment]
The Item and Media configurations are working as expected, but even if I add and save the Resource Class block to item sets and regardless of where I place it on the page values remain the only thing that appears.

**Comment by kimisgold** [comment]
Whoops, that was an oversight. Item sets should be working now.

**Comment by katknow** [comment]
Yes, it's working now! This one should be good to go.
