### ISSUE TITLE
Font-Awesome issue

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-themes/thanksroy#4]
![thanksroy](https://user-images.githubusercontent.com/28012148/227986029-680be4bb-49d9-46d8-b6e0-a5322dd614a7.PNG)

FA icons need a font-weight setting to display on non-active nav links. I think this is `#primary-nav a:hover:before`. The active link's icon is working though, not sure why.

**Comment by kimisgold** [comment]
Provided `font-weight: 900` for all usages of font awesome. Ready for a lookover.
