### ISSUE TITLE
Link colours different between logged in and logged out

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-themes/thanksroy#5]
The navbar seems to be picking up some CSS from the admin bar when logged in? 

![admin1](https://user-images.githubusercontent.com/28012148/227988639-4a38407f-0dd7-49ee-aa33-364ab04f357d.PNG) ![admin2](https://user-images.githubusercontent.com/28012148/227988641-bdd53106-96d3-4329-838e-a51e20fc77c9.PNG)

Logged in vs. logged out. Should be black usually, but appears blue on hover when logged in.

**Comment by kimisgold** [comment]
Unfortunately that would be an accessibility downgrade, so that has to stay.

**Comment by allanaaa** [comment]
Is that really true? All I can find is that visited links should have a high colour contrast to other links, which I don't think we're doing because the colour difference is really subtle, and that there should also be a non-colour differentiation, which we're also not doing. But that all seems to be _if_ we need to do visited links differently, which I can't find any clear writing on. 

https://webaim.org/blog/wcag-2-0-and-link-colors/ just says "if you want" to use multiple states.

**Comment by kimisgold** [comment]
Ah, that's different from what I remembered. That's fine. I can set the default visited link to the same as the main link color, though it will still be a setting for users.
