### ISSUE TITLE
Navbar should expand to active page

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-themes/thanksroy#7]
Another navbar thing; I only just thought to add child items in S, sorry.

When you're on a page that's a submenu item in the navbar, the collapsible menu stays closed. I'd request that it be open to the active page. 

There also seems to be some bold that I would request is only used to indicate the active page, not the whole active section of the menu. Or maybe there's some other way to indicate each status.

![thanksroymenu](https://user-images.githubusercontent.com/28012148/229866966-2a1c416b-4f10-45f8-abf1-6656c46370fb.gif)

**Comment by kimisgold** [comment]
Fixes are in and ready for testing.

**Comment by allanaaa** [comment]
Looks great! Thanks!
