### ISSUE TITLE
Navbar depth error

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-themes/thanksroy#8]
I'm seeing an error in my navbar when I add more layers of depth to it. 

This is happening when the navbar depth is set to 0 in the theme settings, and when it's set to 2 or above. When it's set to 1, it displays properly (i.e. it hides everything after the first level). 

![nav-depth](https://github.com/omeka-s-themes/thanksroy/assets/28012148/93f46751-b391-4d42-8ec5-8fe8aff5a2aa)

**Comment by zerocrates** [comment]
Should be fixed on master
